### ISSUE TITLE
Commiting to pull request via GUI

### ISSUE THREAD

**Issue by atoav** [carrotIndustries/horizon-pool#34]
Maybe a silly question, but I did all my pull requests from before manually with git:  
Can I commit to a pull request via the pool-mgr remote tab somehow?

Lets say I made a pull request, found an error that I want to be corrected (in one of the packages etc). How do I commit the local fixes I made to that pull request? I know how to do it manually via git, but is this possible with the pool-mgr GUI?

**Comment by carrotIndustries** [comment]
You just create a new pull request and close the old one if there's something wrong with the old PR.

I kept the interface as simple as possible so people can commit to the pool without getting familiar with git.

**Comment by atoav** [comment]
I was just wondering if there was something obvious that I didn't see. That means I will go with manual git for now, I like to keep things within one pull request, also helps me to track things better for myself
