### ISSUE TITLE
how to import data from octopart/CPL-Data?

### ISSUE THREAD

**Issue by peterus** [carrotIndustries/horizon-pool#5]
Hi!
Is there a howto, wiki or some scripts how to import data from octopart/CPL-Data?
I would like to add some more things which are already in the CPL-Data lib, but i don't want to start by zero.

**Comment by carrotIndustries** [comment]
Unfortunately, I don't have the script I used to import the resistors and stuff anymore. Which parts are you interested in in particular? Just use your favorite scripting language to generate the requisite json files. Take existing parts as starting point for the files you're going to generate.

**Comment by peterus** [comment]
script created, thx
